682_baseball_game: 682_baseball_game.cpp
	g++ -std=c++11 -o 682_baseball_game 682_baseball_game.cpp
	g++ -std=c++11 -o 496_next_greater_element_I 496_next_greater_element_I.cpp
	g++ -std=c++11 -o 844_backspace_string_compare 844_backspace_string_compare.cpp 
clean:
	rm 682_baseball_game
	rm 496_next_greater_element_I
	rm 844_backspace_string_compare
